export const HOME_REGISTRATION_BEGIN = 'HOME_REGISTRATION_BEGIN';
export const HOME_REGISTRATION_SUCCESS = 'HOME_REGISTRATION_SUCCESS';
export const HOME_REGISTRATION_FAILURE = 'HOME_REGISTRATION_FAILURE';
export const HOME_REGISTRATION_DISMISS_ERROR = 'HOME_REGISTRATION_DISMISS_ERROR';
