export const HOME_REGISTRATION_BEGIN = 'HOME_REGISTRATION_BEGIN';
export const HOME_REGISTRATION_SUCCESS = 'HOME_REGISTRATION_SUCCESS';
export const HOME_REGISTRATION_FAILURE = 'HOME_REGISTRATION_FAILURE';
export const HOME_REGISTRATION_DISMISS_ERROR = 'HOME_REGISTRATION_DISMISS_ERROR';


export const HOME_GETLIST_BEGIN = 'HOME_GETLIST_BEGIN';
export const HOME_GETLIST_SUCCESS = 'HOME_GETLIST_SUCCESS';
export const HOME_GETLIST_FAILURE = 'HOME_GETLIST_FAILURE';
export const HOME_GETLIST_DISMISS_ERROR = 'HOME_GETLIST_DISMISS_ERROR';
export const HOME_LOGIN_BEGIN = 'HOME_LOGIN_BEGIN';
export const HOME_LOGIN_SUCCESS = 'HOME_LOGIN_SUCCESS';
export const HOME_LOGIN_FAILURE = 'HOME_LOGIN_FAILURE';
export const HOME_LOGIN_DISMISS_ERROR = 'HOME_LOGIN_DISMISS_ERROR';
export const HOME_GET_PLACES_BEGIN = 'HOME_GET_PLACES_BEGIN';
export const HOME_GET_PLACES_SUCCESS = 'HOME_GET_PLACES_SUCCESS';
export const HOME_GET_PLACES_FAILURE = 'HOME_GET_PLACES_FAILURE';
export const HOME_GET_PLACES_DISMISS_ERROR = 'HOME_GET_PLACES_DISMISS_ERROR';

